### ISSUE TITLE
nodemon error

### ISSUE THREAD

**Issue by HackIvan** [bhanushalimahesh3/node-website#2]
amor@Rebound:~/node-website$ nodemon start
nodemon: command not found
amor@Rebound:~/node-website$

**Comment by bhanushalimahesh3** [comment]
@HackIvan Looks like nodemon package is not installed

**Comment by sattu444** [comment]
> amor@Rebound:~/node-website$ nodemon start nodemon: command not found amor@Rebound:~/node-websi

> @HackIvan Looks like nodemon package is not installed

I am facing the same issue and I had installed nodemon globally

**Comment by HackIvan** [comment]
Yeah me too
just dunno what's the ish now
:(

**Comment by bhanushalimahesh3** [comment]
@HackIvan @sattu444 it's path issue on your system. Work around for you guys, I hope you know the advantage of using nodemon if not pls read this https://www.npmjs.com/package/nodemon

Workaround 1
Use nodemon not globally but locally, i.e install as your project dependency like any other package
steps
1) npm install nodemon --save-dev
2) after installation done, then in package.json file look for **scripts** key, replace **scripts** key value with **"start" : "nodemon ./bin/www"**
Old 
**"scripts": {
    "start": "node ./bin/www"
  }**
New
**"scripts": {
    "start": "nodemon ./bin/www"
  }**
And from terminal run **npm start**
with this solution you will be able to use nodemon features in same way if installed gobally

Workaround 2
without using nodemon (so won't be able to take advantage of nodemon feature).
From terminal instead of **nodemon start**, write command **npm start**.

Hope both these workaround should work. Let me know if you still face any issues

**Comment by Readtt** [comment]
You can also install it globally, it worked for me
npm install -g nodemon

https://stackoverflow.com/questions/40359590/nodemon-command-is-not-recognized-in-terminal-for-node-js-server
